version: '2.2'
services:
  crawler:
    image: observer
    container_name: observer
    environment:
      - SOKEY=OT*VQMRYOF7h91SNp8hkRQ((
      - SYNCINTERVAL=10
      - USER=demas
      - PASS=root
      - PORT=4000
    volumes:
      - classificator.json:/go/bin/classificator.json
    ports:
      - 4000:4000
  web:
    image: sameersbn/nginx
    container_name: quzx-web
    volumes:
      - /mnt/qnap/quzx/web-dist:/usr/share/nginx/html
    ports:
      - 8085:80
